import React, { useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { Barcode, Download, FileSpreadsheet, PackageCheck, RotateCcw } from "lucide-react";

const aliases = ["tracking no.","tracking no","tracking number","tracking","เลขพัสดุ","เลขติดตามพัสดุ","เลขที่พัสดุ","barcode"];
const clean = (v="") => String(v).replace(/^[\t'\"]+/,"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
const valid = (v) => /^[A-Z0-9]{8,40}$/.test(v);
const parse = (buffer) => {
  const book=XLSX.read(buffer,{type:"array",cellDates:true}), choices=[];
  book.SheetNames.forEach((name)=>{
    const matrix=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:"",raw:false});
    for(let h=0;h<Math.min(matrix.length,12);h+=1){
      const headers=matrix[h].map((x)=>String(x).trim().toLowerCase());
      const col=headers.findIndex((x)=>aliases.includes(x));
      if(col>=0) choices.push(matrix.slice(h+1).map((r)=>({tracking:clean(r[col]),raw:String(r[col]??"").trim()})).filter((r)=>r.raw));
    }
  });
  if(!choices.length) throw new Error("ไม่พบคอลัมน์ Tracking No. หรือ เลขพัสดุ");
  return choices.sort((a,b)=>b.length-a.length)[0];
};

export default function ParcelAudit(){
  const [scan,setScan]=useState([]),[carrier,setCarrier]=useState([]),[scanName,setScanName]=useState(""),[carrierName,setCarrierName]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState("all");
  const read=async(e,kind)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setError("");try{const rows=parse(await file.arrayBuffer());if(!rows.length)throw new Error("ไม่พบเลขพัสดุในไฟล์");if(kind==="scan"){setScan(rows);setScanName(file.name)}else{setCarrier(rows);setCarrierName(file.name)}}catch(err){setError(`${file.name}: ${err.message}`)}};
  const data=useMemo(()=>{const counts=(a)=>a.reduce((m,r)=>{if(valid(r.tracking))m.set(r.tracking,(m.get(r.tracking)||0)+1);return m},new Map());const a=counts(scan),b=counts(carrier);const rows=[...new Set([...a.keys(),...b.keys()])].sort().map((tracking)=>{const sc=a.get(tracking)||0,ca=b.get(tracking)||0;return{tracking,scan:sc,carrier:ca,status:!sc?"missing_scan":!ca?"missing_carrier":"matched",duplicate:sc>1||ca>1}});scan.filter(r=>!valid(r.tracking)).forEach(r=>rows.push({tracking:r.raw,scan:1,carrier:0,status:"invalid",duplicate:false}));carrier.filter(r=>!valid(r.tracking)).forEach(r=>rows.push({tracking:r.raw,scan:0,carrier:1,status:"invalid",duplicate:false}));const summary={scan:scan.length,carrier:carrier.length,matched:rows.filter(r=>r.status==="matched").length,missingScan:rows.filter(r=>r.status==="missing_scan").length,missingCarrier:rows.filter(r=>r.status==="missing_carrier").length,duplicate:rows.filter(r=>r.duplicate).length,invalid:rows.filter(r=>r.status==="invalid").length};return{rows,summary,filtered:rows.filter(r=>filter==="all"||(filter==="duplicate"?r.duplicate:r.status===filter))}},[scan,carrier,filter]);
  const reset=()=>{setScan([]);setCarrier([]);setScanName("");setCarrierName("");setError("");setFilter("all")};
  const exportResult=()=>{const labels={matched:"ตรงกัน",missing_scan:"ไม่มีในไฟล์สแกน",missing_carrier:"ไม่มีในไฟล์ขนส่ง",invalid:"เลขไม่สมบูรณ์"},book=XLSX.utils.book_new(),s=data.summary;XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet([{"ไฟล์สแกน":scanName,"ไฟล์ขนส่ง":carrierName,"รายการสแกน":s.scan,"รายการขนส่ง":s.carrier,"ตรงกัน":s.matched,"ไม่มีในไฟล์สแกน":s.missingScan,"ไม่มีในไฟล์ขนส่ง":s.missingCarrier,"เลขซ้ำ":s.duplicate,"เลขไม่สมบูรณ์":s.invalid}]),"สรุป");XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(data.rows.map((r,i)=>({ลำดับ:i+1,เลขพัสดุ:r.tracking,"จำนวนในไฟล์สแกน":r.scan,"จำนวนในไฟล์ขนส่ง":r.carrier,ผลตรวจสอบ:labels[r.status],เลขซ้ำ:r.duplicate?"ซ้ำ":"ไม่ซ้ำ"}))),"รายละเอียด");XLSX.writeFile(book,`BlueWell-Parcel-Check-${new Date().toISOString().slice(0,10)}.xlsx`)};
  const cards=[["ไฟล์สแกน","scan"],["ไฟล์ขนส่ง","carrier"],["ตรงกัน","matched"],["ไม่มีในไฟล์สแกน","missingScan"],["ไม่มีในไฟล์ขนส่ง","missingCarrier"],["เลขซ้ำ","duplicate"],["เลขไม่สมบูรณ์","invalid"]];
  const label=(s)=>s==="matched"?"ตรงกัน":s==="missing_scan"?"ไม่มีในไฟล์สแกน":s==="missing_carrier"?"ไม่มีในไฟล์ขนส่ง":"เลขไม่สมบูรณ์";
  return <div className="content parcel-audit-page"><section className="panel"><div className="panel-title"><div><h2>ตรวจสอบเลขพัสดุ</h2><p>เทียบไฟล์สแกนพัสดุออฟไลน์กับไฟล์เลขพัสดุจากขนส่ง</p></div><PackageCheck size={24}/></div><div className="parcel-file-grid"><label className={scanName?"parcel-file-card ready":"parcel-file-card"}><Barcode size={28}/><strong>1. ไฟล์สแกนพัสดุออฟไลน์</strong><span>{scanName?`${scanName} · ${scan.length} รายการ`:"รองรับไฟล์ .xlsx, .xls และ .csv"}</span><input type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={e=>read(e,"scan")}/></label><label className={carrierName?"parcel-file-card ready":"parcel-file-card"}><FileSpreadsheet size={28}/><strong>2. ไฟล์เลขพัสดุจากขนส่ง</strong><span>{carrierName?`${carrierName} · ${carrier.length} รายการ`:"รองรับไฟล์ .xlsx, .xls และ .csv"}</span><input type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={e=>read(e,"carrier")}/></label></div>{error&&<p className="error-box">{error}</p>}<p className="info-box">ทั้งสองไฟล์ต้องมีคอลัมน์ Tracking No. หรือ เลขพัสดุ · เปรียบเทียบภายในเบราว์เซอร์และไม่บันทึกลงฐานข้อมูล</p></section>{(scan.length>0||carrier.length>0)&&<><div className="parcel-audit-metrics">{cards.map(([t,k])=><article key={k}><span>{t}</span><strong>{data.summary[k].toLocaleString()}</strong></article>)}</div><section className="panel"><div className="panel-title parcel-result-title"><div><h2>ผลการตรวจสอบ</h2><p>แสดง {data.filtered.length} จาก {data.rows.length} เลข</p></div><div className="parcel-result-actions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="matched">ตรงกัน</option><option value="missing_scan">ไม่มีในไฟล์สแกน</option><option value="missing_carrier">ไม่มีในไฟล์ขนส่ง</option><option value="duplicate">เลขซ้ำ</option><option value="invalid">เลขไม่สมบูรณ์</option></select><button className="btn secondary" onClick={reset}><RotateCcw size={17}/>ล้างข้อมูล</button><button className="btn primary" onClick={exportResult}><Download size={17}/>ส่งออกผล Excel</button></div></div><div className="table-wrap"><table className="parcel-result-table"><thead><tr><th>ลำดับ</th><th>เลขพัสดุ</th><th>ไฟล์สแกน</th><th>ไฟล์ขนส่ง</th><th>ผลตรวจสอบ</th></tr></thead><tbody>{data.filtered.map((r,i)=><tr key={`${r.tracking}-${i}`}><td>{i+1}</td><td><code>{r.tracking}</code></td><td>{r.scan}</td><td>{r.carrier}</td><td><div className="parcel-status"><span className={`badge ${r.status==="matched"?"success":r.status==="invalid"?"neutral":"danger"}`}>{label(r.status)}</span>{r.duplicate&&<span className="badge warning">เลขซ้ำ</span>}</div></td></tr>)}</tbody></table></div></section></>}</div>;
}
